# Generated by Django 5.2.7 on 2025-10-08 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('mensagem', models.TextField()),
                ('lida', models.BooleanField(default=False)),
                ('tipo_notificacao', models.CharField(choices=[('INFO', 'Informativa'), ('ALERT', 'Alerta'), ('PROMOCAO', 'Promoção')], default='INFO', max_length=10)),
                ('grupo_de_envio', models.CharField(choices=[('1', 'Cliente'), ('2', 'Funcionario'), ('3', 'Administrador')], default='1', max_length=1, verbose_name='Tipo de Usuário')),
                ('notificacao_individual', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ativa', models.BooleanField(default=True, help_text='Se a notificação pode ser enviada.')),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='NotificacaoEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lida', models.BooleanField(default=False)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='notificacoes.notificacao')),
            ],
            options={
                'ordering': ['-data_envio'],
            },
        ),
    ]
